# Site settings
title: "Sneh Gupta"
email: 'snehgupta721@gmail.com'
description: "I’m Sneh Gupta, a software developer blending Java expertise with hardware innovation. From crafting efficient code to diving into machine learning, I thrive on building solutions that bridge software and hardware. Let’s turn ideas into reality!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sneh721.github.io" # the base hostname & protocol for your site, e.g. https://example.com
twitter_username: '' # Add your Twitter handle if you have one
github_username: 'sneh721'
medium_username: '' # Add your Medium username if applicable
linkedin_username: 'snehgupta721'
profile_image: 'img/Sneh_photo_2015.jpg'

# Build settings
markdown: kramdown
# theme: phantom # Uncomment once published to RubyGems
plugins:
  - jekyll-paginate

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
paginate: 10
paginate_path: "/page:num/"

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'index'

############################################################

### Phantom settings
footer_text: '© 2025 Sneh Gupta'
admin_name: 'Sneh Gupta'
google_analytics: "" # Add your tracking ID if you use Google Analytics
enable_contact: false

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }
